version: '3.8'

services:
  flask:
    container_name: flask-container-prod
    build:
      context: ./services/backend
      dockerfile: Dockerfile.prod
    ports:
      - 5000:5000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    container_name: db-container-prod
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  vue:
    container_name: vue-container-prod
    build: 
      context: ./services/frontend/
      dockerfile: Dockerfile.prod
    ports:
      - "3000:80"

volumes:
  postgres_data:
